version: '2'
services:
    ifootball2-app:
        image: ifootball2
        external_links:
            - ifootball2-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=iFootball2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ifootball2-mongodb:
        extends:
            file: mongodb.yml
            service: ifootball2-mongodb
