version: '2'
services:
    ifootball2-mongodb:
        container_name: ifootball2-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/iFootball2/mongodb/:/data/db/
