ifootball-postgresql:
  container_name: ifootball-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/iFootball/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=iFootball
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
